### ISSUE TITLE
Odd cut-off bug?

### ISSUE THREAD

**Issue by FireController1847** [lucko/LuckPermsWebEditor#33]
**Description**
If I scroll down on the editor to view a list of permissions, it gets cut off by one permission and when clicking on it all hell breaks loose.

**Reproduce-ability**
I was able to cause this to occur by doing the following commands:
1. `lp creategroup owner`
2. `nucleus setupperms ADMIN owner`
3. `lp group owner editor`

Or... just use this link!
https://lpedit.lucko.me/?ffb0e08f39e7f4520e16e855dcbc0b7f

**Versions**
Nucleus: `v1.2.0-PR5-S7.0`
LuckPerms: `v4.0.72`
LuckPermsWebEditor: https://github.com/lucko/LuckPermsWebEditor/commit/56db620e29445216b2dc7ce1c42d8ecc11a49087

**Images**
Before the click.
![](https://imgur.com/gmTBek7.png)

After the click.
![](https://imgur.com/oCtAJT1.png)

**Comment by BrainStone** [comment]
Ahh I see the issue @lucko 

The strings need to be escaped! As the permission `nucleus.chat.style.<style>` is interpreted as a style block.

I found a simple function to escape: 
```javascript
function escapeHtml(text) {
    'use strict';
    return text.replace(/[\"&'\/<>]/g, function (a) {
        return {
            '"': '&quot;', '&': '&amp;', "'": '&#39;',
            '/': '&#47;',  '<': '&lt;',  '>': '&gt;'
        }[a];
    });
}
```

**Comment by lucko** [comment]
@BrainStone PR?! (pls)

**Comment by BrainStone** [comment]
Lol. Sure, will do once I find time to do it
